#define ERR_SUCCESS 0x0
#define ERR_MEMORY_ALLOCATION_FAILED 0x11
#define ERR_FUNC_FAILED 0x12
#define ERR_WINSOCK_INIT_FAILED 0x13
#define ERR_ADDRINFO_FAILED 0x14
#define ERR_CREATE_EVENT_FAILED 0x15
#define ERR_CREATE_THREAD_FAILED 0x16
#define ERR_CREATE_THREAD_FAILED 0x16
#define ERR_ACCEPT_FAILED 0x17
#define ERR_SET_EVENT_FAILED 0x18
#define ERR_SOCKET_CREATION_FAILED 0x19
#define ERR_SERVER_BIND_FAILED 0x20
#define ERR_SERVER_LISTEN_FAILED 0x21
#define ERR_IOCTLSOCKET_FAILED 0x22

